# Generated by Django 5.0 on 2026-02-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
