# Generated by Django 5.0 on 2026-02-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_education_experience_externallink_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='city_state',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('job_seeker', 'Job Seeker'), ('recruiter', 'Recruiter'), ('admin', 'Admin')], default='job_seeker', max_length=20),
        ),
    ]
