# Generated by Django 5.0 on 2026-02-13 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_phone_number_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='city_state',
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='hide_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='hide_full_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='hide_phone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='hide_profile_photo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='message_filtering',
            field=models.CharField(choices=[('anyone', 'Accept messages from anyone'), ('connections', 'Connections only'), ('none', 'No messages')], default='anyone', max_length=20),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='profile_visibility',
            field=models.CharField(choices=[('public', 'Public - Anyone can view my profile'), ('private', 'Private - Only I can view my profile')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='recruiter_contact_permission',
            field=models.CharField(choices=[('all', 'All Recruiters'), ('none', 'No Recruiters')], default='all', max_length=20),
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
