# Generated by Django 5.0 on 2026-03-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_savedsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='preferred_commute_radius',
            field=models.IntegerField(choices=[(10, '10 miles'), (25, '25 miles'), (50, '50 miles'), (100, '100 miles')], default=25, help_text='Default distance filter for job searches'),
        ),
    ]
