# Generated by Django 5.0 on 2026-03-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_jobseekerprofile_preferred_commute_radius'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='preferred_commute_radius',
            field=models.IntegerField(choices=[(5, '5 miles'), (10, '10 miles'), (15, '15 miles'), (25, '25 miles'), (50, '50 miles'), (75, '75 miles'), (100, '100 miles')], default=25, help_text='Default distance filter for job searches'),
        ),
    ]
